=== panedrone/sqldalmaker/src/resources/dao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="dao-class">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="crud" />
					<xs:element ref="crud-auto" />
					<xs:element ref="query" />
					<xs:element ref="query-list" />
					<xs:element ref="query-dto" />
					<xs:element ref="query-dto-list" />
					<xs:element ref="exec-dml" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="class-name" type="xs:NCName" />
	<xs:attribute name="dto" type="xs:NCName" />
	<xs:attribute name="method" type="xs:string" />
	<xs:attribute name="ref" type="xs:string" />
	<xs:attribute name="external-sql" type="xs:boolean"
		default="false" />
	<xs:attribute name="return-type" type="xs:string" />

	<xs:complexType name="type-method">
		<xs:attribute ref="method" use="required" />
	</xs:complexType>

	<xs:complexType name="type-crud">
		<xs:sequence minOccurs="1">
			<xs:element name="create" type="type-method" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="read-all" type="type-method" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="read" type="type-method" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="update" type="type-method" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="delete" type="type-method" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute ref="dto" use="required" />
		<xs:attribute name="table" type="xs:NCName" use="required" />
		<xs:attribute name="fetch-generated" type="xs:boolean"
			default="true" />
		<xs:attribute name="generated" type="xs:string" default="*" />
	</xs:complexType>

	<xs:element name="crud-auto">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="type-crud" />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="crud">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="type-crud">
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="query">
		<xs:complexType>
			<xs:attribute ref="method" use="required" />
			<xs:attribute ref="ref" use="required" />
			<xs:attribute ref="external-sql" use="optional" />
			<xs:attribute ref="return-type" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="query-list">
		<xs:complexType>
			<xs:attribute ref="method" use="required" />
			<xs:attribute ref="ref" use="required" />
			<xs:attribute ref="external-sql" use="optional" />
			<xs:attribute ref="return-type" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="query-dto">
		<xs:complexType>
			<xs:attribute ref="method" use="required" />
			<xs:attribute ref="dto" use="required" />
			<xs:attribute ref="ref" use="required" />
			<xs:attribute ref="external-sql" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="query-dto-list">
		<xs:complexType>
			<xs:attribute ref="method" use="required" />
			<xs:attribute ref="dto" use="required" />
			<xs:attribute ref="ref" use="required" />
			<xs:attribute ref="external-sql" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="exec-dml">
		<xs:complexType>
			<xs:attribute ref="method" use="required" />
			<xs:attribute ref="ref" use="required" />
			<xs:attribute ref="external-sql" use="optional" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== panedrone/sqldalmaker/harness/fixtures/cpp_task_board/BoardsDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<dao-class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="dao.xsd">

    <query-dto-list method="get_boards" dto="Board" ref="get_boards.sql" />

    <crud dto="Board" table="boards">
        <create method="create_board"/>
        <read-all method="read_board_list"/>
        <read method="read_board"/>
        <update method="update_board"/>
        <delete method="delete_board"/>
    </crud>
    
    <exec-dml method="del_by_range(b_id1, b_id2)" ref="delete from boards where b_id between ? and ?" />

</dao-class>

=== panedrone/sqldalmaker/harness/fixtures/cpp_task_board/TasksDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<dao-class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="dao.xsd">

    <crud dto="Task" table="tasks">
        <create method="create_task"/>
        <read-all method="read_task_list"/>
        <read method="read_task"/>
        <update method="update_task"/>
        <delete method="delete_task"/>
    </crud>

    <query-dto-list method="get_tasks_by_board(b_id)" dto="Task" ref="tasks(b_id)"/>

</dao-class>

=== panedrone/sqldalmaker/harness/fixtures/cpp_task_board/TaskUsersDao.xml
<?xml version="1.0" encoding="UTF-8"?>
<dao-class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dao.xsd">

    <crud dto="TaskUser" table="task_users">
        <create method="createTaskUser"/>
        <read-all method="readTaskUserList"/>
        <read method="readTaskUser"/>
        <update method="updateTaskUser"/>
        <delete method="deleteTaskUser"/>
    </crud>
    <query-dto-list method="getTaskUsersByTask(Integer t_id)" dto="TaskUser" ref="task_users(t_id)"/>
    <query-dto-list method="getTaskUsersByUser(Integer u_id)" dto="TaskUser" ref="task_users(u_id)"/>

</dao-class>
