=== panedrone/sqldalmaker/src/resources/sdm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="sdm">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dto-class" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="dao-class" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="dto-class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="field">
                        <xs:complexType>
                            <xs:attribute name="column" use="required" type="xs:string"/>
                            <xs:attribute name="type" use="required" type="xs:string"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="ref" use="required" type="xs:string"/>
            <xs:attribute name="pk" use="optional" type="xs:string" default="*"/>
            <xs:attribute name="auto" use="optional" type="xs:string" default="*"/>
        </xs:complexType>
        <xs:unique name="field-column">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@column"/>
        </xs:unique>
    </xs:element>

    <xs:element name="dao-class">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="dao-node">
                    <xs:attribute name="name" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="dao-node">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="crud"/>
                <xs:element ref="query"/>
                <xs:element ref="query-list"/>
                <xs:element ref="query-dto"/>
                <xs:element ref="query-dto-list"/>
                <xs:element ref="exec-dml"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:attribute name="dto" type="xs:NCName"/>
    <xs:attribute name="method" type="xs:string"/>
    <xs:attribute name="ref" type="xs:string"/>
    <xs:attribute name="external-sql" type="xs:boolean" default="false"/>
    <xs:attribute name="return-type" type="xs:string"/>

    <xs:complexType name="type-method">
        <xs:attribute ref="method" use="optional"/>
    </xs:complexType>

    <xs:element name="crud">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="create" type="type-method" minOccurs="0" maxOccurs="1"/>
                <xs:element name="read-all" type="type-method" minOccurs="0" maxOccurs="1"/>
                <xs:element name="read" type="type-method" minOccurs="0" maxOccurs="1"/>
                <xs:element name="update" type="type-method" minOccurs="0" maxOccurs="1"/>
                <xs:element name="delete" type="type-method" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="dto" use="required"/>
            <xs:attribute name="table" type="xs:string" use="optional" default="*"/>
            <xs:attribute name="fetch-generated" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="query">
        <xs:complexType>
            <xs:attribute ref="ref" use="required"/>
            <xs:attribute ref="method" use="required"/>
            <xs:attribute ref="external-sql" use="optional"/>
            <xs:attribute ref="return-type" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="query-list">
        <xs:complexType>
            <xs:attribute ref="ref" use="required"/>
            <xs:attribute ref="method" use="required"/>
            <xs:attribute ref="external-sql" use="optional"/>
            <xs:attribute ref="return-type" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="query-dto">
        <xs:complexType>
            <xs:attribute ref="dto" use="required"/>
            <xs:attribute ref="method" use="required"/>
            <xs:attribute ref="ref" use="optional"/>
            <xs:attribute ref="external-sql" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="query-dto-list">
        <xs:complexType>
            <xs:attribute ref="dto" use="required"/>
            <xs:attribute ref="method" use="required"/>
            <xs:attribute ref="ref" use="optional"/>
            <xs:attribute ref="external-sql" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="exec-dml">
        <xs:complexType>
            <xs:attribute ref="ref" use="required"/>
            <xs:attribute ref="method" use="required"/>
            <xs:attribute ref="external-sql" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== panedrone/sqldalmaker/harness/fixtures/cpp_task_board/sdm.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="sdm.xsd">

    <!-- Migrated from "sdm/dto.xml" of "D:/work/sdm-cpp/qt6_sqlite3_task_board":
         "<dto-classes>" -> "<sdm>", "java-type" -> "type", plus the "<dao-class ref=..."
         registrations that "dto.xml" did not have. Nothing else was changed. -->

    <dto-class name="Board" ref="get_boards.sql">
        <field type="Integer" column="b_id"/>
        <field type="String" column="b_dt_created"/>
        <field type="String" column="b_dt_updated"/>
        <field type="String" column="b_name"/>
        <field type="Integer" column="b_tasks_count"/>
    </dto-class>

    <dto-class name="Task" ref="tasks"/>

    <dto-class name="NoAiPk" ref="_no_ai_pk"/>

    <dto-class name="TaskUser" ref="task_users"/>
    <dto-class name="User" ref="users"/>

    <dao-class name="BoardsDao" ref="BoardsDao.xml"/>
    <dao-class name="TasksDao" ref="TasksDao.xml"/>
    <dao-class name="TaskUsersDao" ref="TaskUsersDao.xml"/>
    <dao-class name="UserDao" ref="UserDao.xml"/>
    <dao-class name="NoAiPkDao" ref="NoAiPkDao.xml"/>

</sdm>
