=== panedrone/sqldalmaker/src/resources/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="folders"/>
                <xs:element ref="dto"/>
                <xs:element ref="dao"/>
                <xs:element ref="ide"/>
                <xs:element ref="jdbc"/>
                <xs:element ref="db" minOccurs="0"/>
                <xs:element ref="type-map"/>
                <xs:element ref="macros"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="folders">
        <xs:complexType>
            <xs:attribute name="target" use="required" type="xs:string"/>
            <xs:attribute name="sql" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dto">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="inheritance" use="required" type="xs:string"/>
            <xs:attribute name="field-names-mode" use="required" type="xs:int"/>
            <xs:attribute name="macro" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dao">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="field-assign-mode" use="required" type="xs:int"/>
            <xs:attribute name="macro" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ide">
        <xs:complexType>
            <xs:attribute name="event-log" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jdbc">
        <xs:complexType>
            <xs:attribute name="jar" use="required" type="xs:string"/>
            <xs:attribute name="class" use="required" type="xs:string"/>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="required" type="xs:string"/>
            <xs:attribute name="pwd" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="db">
        <xs:annotation>
            <xs:documentation>The database of sdmc (https://github.com/panedrone/sdmc).
                The IDE plug-ins use "jdbc" and ignore "db".</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="optional" type="xs:string"/>
            <xs:attribute name="pwd" use="optional" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type-map">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="default" use="required"
                          type="xs:string"/>
        </xs:complexType>
        <xs:unique name="type-detected">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@detected"/>
        </xs:unique>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:attribute name="detected" use="required" type="xs:string"/>
            <xs:attribute name="target" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="macros">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="macro">
                        <xs:complexType>
                            <xs:choice minOccurs="0">
                                <xs:element name="vm" type="xs:string" minOccurs="0"/>
                                <xs:element ref="vm-xml" minOccurs="0"/>
                            </xs:choice>
                            <xs:attribute ref="name" use="required"/>
                            <xs:attribute ref="value" use="optional"/>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="macro-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:attribute name="var" type="xs:string"/>
    <xs:attribute name="in" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="params" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>

    <xs:complexType name="root-statements">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice>
                <xs:element ref="if"/>
                <xs:element ref="set"/>
                <xs:element ref="foreach"/>
                <xs:element ref="macro"/>
                <xs:element ref="print"/>
                <xs:element ref="br"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="vm-xml">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="if">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="else">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreach">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                    <xs:attribute ref="in" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="name" use="required"/>
                    <xs:attribute ref="params" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="set">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="print">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attribute name="br" default="" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== panedrone/sqldalmaker/src/resources/data_store_no_orm.go.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!--    (*) below means "a path relative to the project root"   -->

    <!-- target: the same as "module" in "go.mod" -->

    <!-- sql: base folder of SQL files (*) -->

    <folders target="sdm_demo_todolist" sql="sqlx/sdm/sql"/>

    <!-- scope: base folder of generated DTO files (*) -->

    <!-- field-names-mode: 0 - TitleCase -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dto ... macro="<path>/<name>.vm"/> -->

    <dto scope="no_orm/dbal/dto" inheritance="" field-names-mode="0" macro=""/>

    <!-- scope: base folder of generated DAO files (*) -->

    <!-- field-assign-mode (Go only)":

            0 - by column name (database/sql, gorm)
            1 - by field position (unsafe)
            2 - ptr to DTO or ptr to slice of DTO-s (gorm, sqlx)
            3 - ptr to resulting slice of DTO-s (gorm, sqlx) -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dao ... macro="<path>/<name>.vm"/> -->

    <dao scope="no_orm/dbal" field-assign-mode="3" macro=""/>

    <ide event-log="true"/>

    <!--    <jdbc jar="lib/sqlite-jdbc-3.45.1.0.jar" class="org.sqlite.JDBC"-->
    <!--          url="jdbc:sqlite:$PROJECT_DIR$/db/todolist.sqlite" user="" pwd=""/>-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <!--    <jdbc jar="mysql-connector-j-8.4.0.jar"-->
    <!--          class="com.mysql.cj.jdbc.Driver" url="jdbc:mysql://localhost/orders" user="root" pwd="sa"/>-->

    <jdbc jar="postgresql-42.7.3.jar" class="org.postgresql.Driver"
          url="jdbc:postgresql://localhost/orders" user="postgres" pwd="sa"/>

    <type-map default="">

        <!-- sqlite3 -->

        <!--        <type detected="java.lang.Integer" target="int64${json} -> SetInt64"/>-->
        <!--        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="byte[]" target="[]byte${json} -> SetBytes"/>-->
        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

        <!-- mysql, postgres, sql server -->

        <type detected="java.util.UUID" target="github.com/google/uuid:uuid.UUID${json} -> Scan"/>
        <type detected="java.sql.Array" target="[]string${json}"/>

        <type detected="java.lang.Short" target="int16${json} -> SetInt16"/>
        <type detected="java.lang.Integer" target="int32${json} -> SetInt32"/>
        <type detected="java.lang.Long" target="int64${json} -> SetInt64"/>

        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>
        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>
        <type detected="java.math.BigDecimal" target="float64${json} -> SetFloat64"/>

        <type detected="java.lang.String" target="string${json} -> SetString"/>
        <type detected="byte[]" target="[]byte${json} -> SetBytes"/>
        <type detected="java.lang.Boolean" target="bool${json} -> SetBool"/>

        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>
        <type detected="java.time.LocalDateTime" target="time:time.Time${json} -> SetTime"/>

        <type detected="java.lang.Object" target="interface{}${json}"/>

        <!-- oracle -->

        <!--        <type detected="java.math.BigDecimal" target="${json-ora-num}"/>-->
        <!--        <type detected="java.math.BigDecimal+auto" target="${json-ora-num}"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->

        <!--        <type detected="java.util.Date" target="${json-time}"/>-->
        <!--        <type detected="java.time.ZonedDateTime" target="${json-time}"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="${json-time}"/>-->

        <!--        <type detected="byte[]" target="string${json} -> SetBytes"/>-->
        <!--        <type detected="java.lang.Boolean" target="int64${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}{$json}"/>-->

    </type-map>

    <macros>

        <macro value="=built-in=" name="${column}"/>
        <macro value="=built-in=" name="${lower_snake_case(column)}"/>
        <macro value="=built-in=" name="${camelCase(column)}"/>
        <macro value="=built-in=" name="${TitleCase(column)}"/>
        <macro value="=built-in=" name="${kebab-case(column)}"/>

        <macro name="${json-col}" value="${lower_snake_case(column)}"/>

        <macro name="${json}" value=" `json:&quot;${json-col}${0}&quot;`"/>

        <macro name="${json-time}" value="time:time.Time${json} -> SetTime"/>

        <macro name="${json-ora-num}" value="${ora-num} `json:&quot;${json-col}${0}&quot;` -> SetNum"/>

        <macro name="${ora-num}">
            <vm-xml>
                <if var="$fi.Precision == 38 &amp;&amp; $fi.Scale == 0">
                    <print var=" int64"/>
                    <else>
                        <print var=" github.com/godror/godror:godror.Number"/>
                    </else>
                </if>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/harness/fixtures/refcursors_java/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <folders target="src" sql="sdm/sql"/>

    <dto scope="dto" inheritance="" field-names-mode="1" macro=""/>

    <dao scope="dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="sdm/sqlite-jdbc-3.32.3.2.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/task_tracker.sqlite" user="" pwd=""/>

    <type-map default="">
    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore_Doctrine_ORM.php.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root). -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="api" sql="sdm/sql"/>

    <!-- scope: the name of DTO namespace. An empty one is OK. -->

    <!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

    <dto scope="svc/models" inheritance="" field-names-mode="2" macro=""/>

    <!-- scope: the name of DTO namespace. An empty one is OK. -->

    <dao scope="svc/dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="mysql-connector-j-26.7.0.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <type-map default="">

        <!-- ******   PHP Doctrine   ****** -->

        <!-- https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html-->

        <type detected="doctrine-java.lang.Short" target="${doctrine-type}|0:smallint|1:int"/>
        <type detected="doctrine-java.lang.Integer" target="${doctrine-type}|0:integer|1:int"/>
        <type detected="doctrine-java.lang.Long" target="${doctrine-type}|0:bigint|1:string"/>

        <type detected="doctrine-java.lang.Float" target="${doctrine-type}|0:float|1:float"/>
        <type detected="doctrine-java.lang.Double" target="${doctrine-type}|0:float|1:float"/>
        <type detected="doctrine-java.math.BigDecimal" target="${doctrine-type}|0:decimal|1:string"/>

        <type detected="doctrine-java.util.Date" target="${doctrine-type}|0:datetime|1:\DateTime"/>
        <type detected="doctrine-java.lang.String" target="${doctrine-type}|0:string|1:string"/>
        <type detected="doctrine-java.lang.Boolean" target="${doctrine-type}|0:boolean|1:bool"/>
        <type detected="doctrine-byte[]" target="${doctrine-type}|0:array|1:array"/>
        <type detected="doctrine-java.lang.Object" target="${doctrine-type}|0:object|1:object"/>

        <!-- ******   PHP scalar types  ****** -->

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="int"/>

        <type detected="java.lang.Float" target="float"/>
        <type detected="java.lang.Double" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="string"/>
        <type detected="java.lang.String" target="string"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="array"/>
        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>

        <!-- =built-in= is a key-word -->

        <macro name="${column}" value="=built-in="/>
        <macro name="${lower_snake_case(column)}" value="=built-in="/>
        <macro name="${camelCase(column)}" value="=built-in="/>
        <macro name="${TitleCase(column)}" value="=built-in="/>
        <macro name="${kebab-case(column)}" value="=built-in="/>

        <!-- PHP Doctrine ORM field type: -->

        <!-- https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/attributes-reference.html#attrref_column-->

        <macro name="${doctrine-type}">
            <vm-xml>
                <print var="@ORM\Column(name=&quot;${column}&quot;, type=&quot;${0}&quot;"/>
                <if var="$fi.ColumnSize>0">
                    <print var=", length=$fi.ColumnSize"/>
                </if>
                <if var="!$fi.PK">
                    <if var="$fi.Unique">
                        <print var=", unique=true"/>
                    </if>
                    <if var="$fi.Nullable">
                        <print var=", nullable=true"/>
                    </if>
                </if>
                <print var=")"/>
                <if var="$fi.PK">
                    <br/>
                    <br/>
                    <print var="     * @ORM\Id"/>
                </if>
                <if var="$fi.AI">
                    <br/>
                    <br/>
                    <print var="     * @ORM\GeneratedValue"/>
                </if>
                <br/>
                <br/>
                <print var="     * @var ${1}"/>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/harness/fixtures/cpp_task_board/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- Migrated from "sdm/settings.xml" of "D:/work/sdm-cpp/qt6_sqlite3_task_board".
         Same values, current attribute names: "<type java=" -> "<type detected=",
         "<external-vm-file>" and "<cpp class-prefix>" are gone, "macro" and
         "field-assign-mode" are now required. "jar", "url" and "sql" are still
         relative to the project dir, i.e. to the demo project, not to this folder. -->

    <folders target="" sql="sdm/sql"/>

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="sdm/sqlite-jdbc-3.32.3.2.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/task_tracker.sqlite" user="" pwd=""/>

    <type-map default="CValue">
        <type detected="java.lang.Integer" target="CInteger"/>
        <type detected="java.lang.Long" target="CLong"/>
        <type detected="java.lang.Double" target="CDouble"/>
        <type detected="java.lang.String" target="CText"/>
        <type detected="byte[]" target="CBlob"/>
    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore.java.JDBC.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root). -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="src" sql="sdm/sql"/>

    <!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

    <!-- scope: the name of DTO package -->

    <dto scope="com.sdm.thesaurus.dto" inheritance="" field-names-mode="1" macro=""/>

    <!-- scope: the name of DAO package -->

    <dao scope="com.sdm.thesaurus.dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="sdm/sqlite-jdbc-3.41.2.1.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/thesaurus.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="lib/mysql-connector-j-26.7.0.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/sakila" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.2.9.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/orders" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="lib/ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521:XE" user="orders" pwd="sa"/>-->

    <!--    <jdbc jar="mssql-jdbc-8.2.2.jre8.jar" class="com.microsoft.sqlserver.jdbc.SQLServerDriver"-->
    <!--          url="jdbc:sqlserver://localhost:1433;instance=SQLEXPRESS;databaseName=AdventureWorks2014" user="sa" pwd="root"/>-->

    <type-map default="">

        <type detected="java.lang.Short" target="Short -> getShort"/>
        <type detected="java.lang.Integer" target="Integer -> getInteger"/>
        <type detected="java.lang.Long" target="Long -> getLong"/>

        <type detected="java.lang.Float" target="Float -> getFloat"/>
        <type detected="java.lang.Double" target="Double -> getDouble"/>
        <type detected="java.math.BigDecimal" target="java.math.BigDecimal -> getBigDecimal"/>

        <type detected="java.lang.String" target="String -> getString"/>
        <type detected="java.util.Date" target="java.util.Date -> getDate"/>
        <type detected="byte[]" target="byte[] -> getBytes"/>
        <type detected="java.lang.Boolean" target="Boolean -> getBoolean"/>

    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore.cpp.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <folders target="" sql="sqldalmaker/sql" />

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <type-map default="CValue">
        <type detected="java.lang.Integer" target="CLong" />
        <type detected="java.lang.Long" target="CLong" />
        <type detected="java.lang.Double" target="CDouble" />
        <type detected="java.lang.String" target="CText" />
        <type detected="byte[]" target="CBlob" />
    </type-map>

    <macros>
    </macros>

</settings>
